import {
  SIGNUP_COMPLETION,
  SIGNUP_PHONE,
  SIGNUP_TERMS,
  SIGNUP_PASSWORD,
  SIGNUP_EMAIL,
} from './page-url /sign-up';

import { TERM_SERVICE, TERM_MARKETING, TERM_PRIVACY } from './page-url /terms';

export {
  SIGNUP_COMPLETION,
  SIGNUP_PHONE,
  SIGNUP_TERMS,
  SIGNUP_PASSWORD,
  SIGNUP_EMAIL,
};

export { TERM_PRIVACY, TERM_MARKETING, TERM_SERVICE };
