import {
  SIGNUP_COMPLETION,
  SIGNUP_PHONE,
  SIGNUP_TERMS,
  SIGNUP_PASSWORD,
  SIGNUP_EMAIL,
} from './page-url /sign-up';

export {
  SIGNUP_COMPLETION,
  SIGNUP_PHONE,
  SIGNUP_TERMS,
  SIGNUP_PASSWORD,
  SIGNUP_EMAIL,
};
