import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import BottomNav from '../components/nav/bottom_nav';
import { ProductModel } from '../models/model/product';
import ProductViewModel from '../models/view-model/product';
import 'swiper/css';
import Banner from '../components/common/banner/banner';
import AppBar from '../components/nav/app_bar';
import HomeProductBox from '../components/home/homeProductBox';
import BuckitNews from '../components/home/buckit_news';

const Home: NextPage = () => {
  const productModel: ProductModel = new ProductModel();
  const productViewModel: ProductViewModel = new ProductViewModel(productModel);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <AppBar />

          <Banner />

          <h3 className={styles.recommend_title}>
            사장님 이 프로젝트는 어때요?
          </h3>
          <HomeProductBox productViewModel={productViewModel} />

          <h3 className={styles.recommend_title}>버킷 뉴스</h3>
          <div className={styles.news_container}>
            <BuckitNews />
          </div>

          <div className={styles.company_information}>
            주식회사 버닝서프라이즈
            <br />
            서울특별시 서대문구 연세로2다길 19, 201호
            <br />
            대표자 : 최단비 | 사업자등록번호 : 678-88-02357
            <br />
            대표 번호 : 070-8095-2257
          </div>

          <BottomNav />
        </div>
      </main>
    </div>
  );
};

export default Home;
